spring.application.name=ViviEstu_api
#Ruta para api endpoints


# --- Configuracion de PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/viviestu_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server.port=8080
